// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetStoreInventory.Data;

#nullable disable

namespace PetStoreInventory.Migrations
{
    [DbContext(typeof(PetStoreContext))]
    [Migration("20240718130336_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetStoreInventory.Models.PetDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Chipnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Contactpersoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DatumVanBinnenkomst")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diersoort")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gedrag")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Geslacht")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Gewicht")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Gezondheidsstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Leeftijd")
                        .HasColumnType("int");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Ras")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vaccinatiestatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Verkoopstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Voeding")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PetStore");
                });
#pragma warning restore 612, 618
        }
    }
}
